//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SyncMessage.proto
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private float _highestScore;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"highestScore", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float highestScore
    {
      get { return _highestScore; }
      set { _highestScore = value; }
    }
    private int _ranking;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private PBMessage.UserInfo.Status _status;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.UserInfo.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _killNumber;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"killNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killNumber
    {
      get { return _killNumber; }
      set { _killNumber = value; }
    }
    private int _deathNumber;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"deathNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deathNumber
    {
      get { return _deathNumber; }
      set { _deathNumber = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Status")]
    public enum Status
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONLIEN", Value=0)]
      ONLIEN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE", Value=1)]
      OFFLINE = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageLogin")]
  public partial class MessageLogin : global::ProtoBuf.IExtensible
  {
    public MessageLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _channel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageLogout")]
  public partial class MessageLogout : global::ProtoBuf.IExtensible
  {
    public MessageLogout() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WeaponInfo")]
  public partial class WeaponInfo : global::ProtoBuf.IExtensible
  {
    public WeaponInfo() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private PBMessage.WeaponInfo.WeaponType _weaponType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"weaponType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.WeaponInfo.WeaponType weaponType
    {
      get { return _weaponType; }
      set { _weaponType = value; }
    }
    private string _target;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"WeaponType")]
    public enum WeaponType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MachineGun", Value=0)]
      MachineGun = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlasmaGun", Value=1)]
      PlasmaGun = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JetFlame", Value=2)]
      JetFlame = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LightShield", Value=3)]
      LightShield = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FireWhirlwind", Value=4)]
      FireWhirlwind = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Missile", Value=5)]
      Missile = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OrdinaryGun", Value=6)]
      OrdinaryGun = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=7)]
      None = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector4")]
  public partial class Vector4 : global::ProtoBuf.IExtensible
  {
    public Vector4() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _w;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector2")]
  public partial class Vector2 : global::ProtoBuf.IExtensible
  {
    public Vector2() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransformData")]
  public partial class TransformData : global::ProtoBuf.IExtensible
  {
    public TransformData() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private float _cf;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cf", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float cf
    {
      get { return _cf; }
      set { _cf = value; }
    }
    private PBMessage.Vector3 _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private PBMessage.Vector4 _rot;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Vector4 rot
    {
      get { return _rot; }
      set { _rot = value; }
    }
    private PBMessage.Vector3 _velocity;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"velocity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Vector3 velocity
    {
      get { return _velocity; }
      set { _velocity = value; }
    }
    private PBMessage.Vector3 _angularVelocity;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"angularVelocity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Vector3 angularVelocity
    {
      get { return _angularVelocity; }
      set { _angularVelocity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirectionSpeedData")]
  public partial class DirectionSpeedData : global::ProtoBuf.IExtensible
  {
    public DirectionSpeedData() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private float _angle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private bool _mRockerIsMove;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mRockerIsMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool mRockerIsMove
    {
      get { return _mRockerIsMove; }
      set { _mRockerIsMove = value; }
    }
    private PBMessage.Vector2 _circularAngle;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"circularAngle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Vector2 circularAngle
    {
      get { return _circularAngle; }
      set { _circularAngle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WeaponGunRotate")]
  public partial class WeaponGunRotate : global::ProtoBuf.IExtensible
  {
    public WeaponGunRotate() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private bool _isAttack;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isAttack
    {
      get { return _isAttack; }
      set { _isAttack = value; }
    }
    private float _angle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageGenerateExistedClients")]
  public partial class MessageGenerateExistedClients : global::ProtoBuf.IExtensible
  {
    public MessageGenerateExistedClients() {}
    
    private readonly global::System.Collections.Generic.List<string> _clients = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"clients", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> clients
    {
      get { return _clients; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectInfo")]
  public partial class ObjectInfo : global::ProtoBuf.IExtensible
  {
    public ObjectInfo() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private float _MaxHp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MaxHp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float MaxHp
    {
      get { return _MaxHp; }
      set { _MaxHp = value; }
    }
    private float _Hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
    private float _AtkValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"AtkValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float AtkValue
    {
      get { return _AtkValue; }
      set { _AtkValue = value; }
    }
    private float _DefValue;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DefValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DefValue
    {
      get { return _DefValue; }
      set { _DefValue = value; }
    }
    private float _Level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private float _Score;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private int _KillNumber;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"KillNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int KillNumber
    {
      get { return _KillNumber; }
      set { _KillNumber = value; }
    }
    private int _DeathNumber;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"DeathNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DeathNumber
    {
      get { return _DeathNumber; }
      set { _DeathNumber = value; }
    }
    private PBMessage.ObjectInfo.ObjectType _objectType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"objectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.ObjectInfo.ObjectType objectType
    {
      get { return _objectType; }
      set { _objectType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ObjectType")]
    public enum ObjectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Min", Value=0)]
      Min = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bitch", Value=1)]
      Bitch = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Angel", Value=2)]
      Angel = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Toilet", Value=3)]
      Toilet = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Villa", Value=4)]
      Villa = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Max", Value=5)]
      Max = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageOnDeath")]
  public partial class MessageOnDeath : global::ProtoBuf.IExtensible
  {
    public MessageOnDeath() {}
    
    private string _Attacker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Attacker
    {
      get { return _Attacker; }
      set { _Attacker = value; }
    }
    private string _Dead;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Dead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Dead
    {
      get { return _Dead; }
      set { _Dead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrdinaryGunAttack")]
  public partial class OrdinaryGunAttack : global::ProtoBuf.IExtensible
  {
    public OrdinaryGunAttack() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private bool _Attack;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Attack
    {
      get { return _Attack; }
      set { _Attack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}